# Site settings
title:       Hakan Dilek
email:       hakan@dilek.me
author:      Hakan Dilek
description: "My personal blog"
baseurl:     ""
url:         "http://www.dilek.me"

# Google analytics
google_analytics: UA-60180717-1

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: dilekme

# Social icons
show_social_icons: false
github_username: hakandilek
stackoverflow_id: 430718
twitter_username: panikyok
google_plus_id: 111385467094694549256
linkedin_username: hakan
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true

# Gems
gems: [jekyll-paginate]
