baseURL = "https://www.dilek.me/"
languageCode = "en-us"
title = "Hakan Dilek"
theme = "ananke"
disqusShortname = "dilekme"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = "UA-60180717-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "My personal blog"
  facebook = ""
  twitter = "https://twitter.com/panikyok"
  instagram = ""
  youtube = ""
  github = "https://github.com/hakandilek"
  gitlab = "https://gitlab.com/hd"
  linkedin = "https://www.linkedin.com/in/hakan/"
  mastodon = ""
  slack = ""
  stackoverflow = "https://stackoverflow.com/users/430718/hakan-dilek"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 4
